# ===================================================
# ====== Configuration File of 'BankingPlugin' ======
# ===================================================
#
#

# Set the main command names to be used for bank management, account management, and system control in this plugin.
# Type: String
# Defaults: "bank", "account", "bankingplugin"
main-command-names:
  bank: bank
  account: account
  control: bankingplugin

# Set the hours at which players should receive interest payments from their accounts.
# These are real times (0 <= time < 24) represented as normal double values (e.g. 3:30 in the
# afternoon would be written as 15.50, or "the fifteenth hour plus one-half hour").
# The conversion happens by multiplying everything after the decimal point by 60 and rounding down.
# Some useful conversions:
#   10 minutes = .17        15 minutes = .25      30 minutes = .50    45 minutes = .75      50 minutes = .84
# Equivalent values will be joined together.
# Type: List<Double>
# Default: 9, 15, 21
interest-payout-times:
  -9
  -12
  -15
  -18
  -21
  
# Set the baseline interest rate for all bank accounts on the server.
# Value should be a float between 0 and 1.
# Type: double
# Default: 0.01 (for 1% interest)
baseline-interest-rate: 0.01

# Set this value to enable/disable interest multipliers.
# Type: boolean
# Default: true
enable-interest-multipliers: true

# Set the consecutive interest multipliers that are applied per-player to the baseline multiplier.
# Each value represents a "stage" to be progressed through in consecutive order.
# Players advance through the multipliers by being online to collect interest more than once in a row.
# At least the first value should be 1, so that the baseline interest rate is used.
# For example: setting the sequence [1, 2, 2, 3, 3, 3, 4, 4, 4, 4] would result in one 1x multiplier stage,
# two 2x stages, three 3x stages, and four 4x stages.
# Multipliers will never go past the final stage, nor further back than the first stage.
# Type: List<Integer>
interest-multipliers:
  -1
  -2
  -3
  

# Set the number of interest payout events a player must own their account for
# before they start collecting interest.
# Set to 0 to start collecting interest immediately after creating the account.
# Type: int
# Default: 0
interest-delay-period: 0

# Whether to decrement the interest delay period while a player is offline. 
# Set this to false to only decrement the delay period when a player is online for
# an interest payout event, and not while offline.
# Type: boolean
# Default: false
interest-delay-count-while-offline: false

# Set the number of times a player can be offline and still collect interest on their accounts.
# Set this to 0 for no interest while offline.
# Type: short
# Default: 1
allowed-offline-payouts: 1

# Set the number of times a player can be offline at the interest payout times before their multiplier is reset.
# This is independent of the number of times a player can collect interest payouts offline.
# A player could continue to receive baseline interest payouts offline after the multiplier reset if allowed-offline-payouts is set higher than this.
# If allowed-offline-payouts is set lower than this, an offline player will stop receiving payouts but will not lose their multiplier
# until after they are offline for this number of interest payout times.
# Set this value to 0 for a no-tolerance policy on missing payouts (multiplier reset at first offline payout)
# Type: short
# Default: 1
allowed-offline-payouts-before-multiplier-reset: 1

# Set the behavior of the interest multiplier while a player is offline.
# Setting this value to -1 causes the multiplier to decrease by one stage per payout time while the player is offline.
# Setting this value to 0 causes the multiplier to freeze until the player comes back online. It will remain the same as long as it is not reset.
# Setting this value to 1 causes the multiplier to iterate like normal, even when the player is offline (discouraged)
# Absolute values greater than 1 *are* allowed, but to be used sparingly (-2 would decrease a player's multiplier by two stages for every missed payout)
# Type: short
# Default: 0
offline-multiplier-behavior: 0

# Set the behavior of the interest multiplier when the player makes a withdrawal.
# Setting this value to -1 causes the multiplier to decrease by one stage per withdrawal.
# Setting this value to 0 causes the multiplier to not be affected by withdrawals (discouraged)
# Setting this value to any positive integer causes the multiplier to be RESET when the player makes a withdrawal.
# Type: short
# Default: 1
withdrawal_multiplier_behavior: 1

# Set the item with which a player can click a account to retrieve information.
# You can set this to an empty string ("") to disable this feature.
# Type: String, converted to ItemStack
# Default: "STICK"
account-info-item: "STICK"

# Set the price a player has to pay in order to create...
# You can set this to 0 to disable costs.
# Type: double
creation-prices:
# bank: 100
  account: 25

# Set whether the (current) account creation price should be refunded
# when the account is removed by its creator.
# Type: boolean
reimburse-account-creation: false

# Set whether to require confirmation of remove commands on the server.
# Type: boolean
# Default: true
confirm-on-remove: true

# Set whether to require confirmation of removeall commands on the server.
# Type: boolean
# Default: true
confirm-on-removeall: true

# Set the delay, in ticks, before a removeall command should be executed on
# the server. Set to zero for no delay. Defaults to 600 ticks if negative.
# Type: int
# Default: 300
removeall-delay: 300

# Set insurance for every account on the server in case of chest corruption (not expected).
# Account owners will be reimbursed what was lost up to this amount.
# Set this value to -1 for no limit.
# Type: long
insure-accounts-up-to: 250000

# Set whether the plugin will check for updates on server start
# and notify permitted players on join.
# The command is not affected by this setting and will continue to
# check for updates.
# Type: boolean
# Default: true
enable-update-checker: true

# Set whether deposits/withdrawals, interest payouts, and debug logs should be saved in the database.
# Debug log file may become quite large!
# Type: boolean
enable-logs:
  transaction-log: false
  interest-log: true
  debug-log: false

# Set the maximum age for economy log entries in days.
# All log entries older than this will be deleted on server start.
# Set this to 0 to disable this feature.
# Type: short
# Default: 30
cleanup-log-days: 30

# Set whether various protection plugins should be hooked into (if installed)
# in order to allow or deny bank or account creation in certain locations.
enable-worldguard-integration: true
enable-griefprevention-integration: true
enable-worldedit-integration: true

# Set whether accounts should automatically be removed from the database if
# an error occurred while loading.
# (e.g. no chest, no space above chest, or unknown world)
remove-account-on-error: false

# Set the items for which a player will earn no interest in their account.
blacklist:
# - "DIORITE"


# Account limits are handled with permissions.
# A player with permission "bankingplugin.account.limit.X" has a limit of X accounts,
# a player with permission "bankingplugin.account.limit.*" does not have an account limit.
default-limits:

  # Set the amount of accounts that anyone who doesn't have a
  # specific permission may have.
  # If you don't want the players to have a limit by default
  # set the value to -1.
# bank: 1
  account: -1

# Set whether the custom WorldGuard flags should be allowed by default.
worldguard-default-flag-values:

  create-bank: false
  create-account: false
  
# Set the prefix of all SQLite table names related to this plugin.
table-prefix: "bankingplugin_"
