# ===================================================
# ====== Configuration File of 'BankingPlugin' ======
# ===================================================
#
#

# Set the main command names to be used for bank management, account management, and system control in this plugin.
# Type: String
# Defaults: "bank", "account", "bankingplugin"
main-command-names:
  bank: bank
  account: account
  control: bp

# Set the hours at which players should receive interest payments from their accounts.
# These are real times (0 <= time < 24) represented as normal double values (e.g. 3:30 in the
# afternoon would be written as 15.50, or "the fifteenth hour plus one-half hour").
# The conversion happens by multiplying everything after the decimal point by 60 and rounding down.
# Some useful conversions:
#   10 minutes = .17        15 minutes = .25      30 minutes = .50    45 minutes = .75      50 minutes = .84
# Equivalent values will be joined together.
# Type: List<Double>
# Default: 9, 15, 21
interest-payout-times:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 20
  
# Set the base interest rate for all bank accounts on the server.
# Value should be a floating point number greater than 0.
# Type: double
# Default: 0.01 (for 1% interest)
interest-rate:
    default: 0.01
    allow-override: true # This boolean determines whether or not individual banks have permission to override the default value.

# Set the consecutive interest multipliers that are applied per-player to the baseline multiplier.
# Each value represents a "stage" to be progressed through in consecutive order.
# Players advance through the multipliers by being online to collect interest more than once in a row.
# At least the first value should be 1, so that the baseline interest rate is used.
# For example: setting the sequence [1, 2, 2, 3, 3, 3, 4, 4, 4, 4] would result in one 1x multiplier stage,
# two 2x stages, three 3x stages, and four 4x stages.
# Multipliers will never go past the final stage, nor further back than the first stage.
# Type: List<Integer>
interest-multipliers:
    default:
        - 1
    allow-override: true

# Set the number of interest payout events a player must own their account for
# before they start collecting interest on that account.
# Set to 0 to start collecting interest immediately after creating the account.
# Type: int
# Default: 0
initial-interest-delay:
    default: 0
    allow-override: true

# Whether to decrement the interest delay period while a player is offline. 
# Set this to false to only decrement the delay period when a player is online for
# an interest payout event, and not while offline.
# Type: boolean
# Default: false
count-interest-delay-offline:
    default: false
    allow-override: false

# Set the number of times a player can be offline and still collect interest on their accounts.
# Set this to 0 for no interest while offline.
# Type: int
# Default: 1
allowed-offline-payouts:
    default: 1
    allow-override: true

# Set the number of times a player can be offline at the interest payout times before their multiplier is reset.
# This is independent of the number of times a player can collect interest payouts offline.
# A player could continue to receive baseline interest payouts offline after the multiplier reset if allowed-offline-payouts is set higher than this.
# If allowed-offline-payouts is set lower than this, an offline player will stop receiving payouts but will not lose their multiplier
# until after they are offline for this number of interest payout times.
# Set this value to 0 for a no-tolerance policy on missing payouts (multiplier reset at first offline payout)
# Type: int
# Default: 1
allowed-offline-payouts-before-multiplier-reset:
    default: 1
    allow-override: true

# Set the behavior of the interest multiplier while a player is offline.
# Setting this value to -1 causes the multiplier to decrease by one stage per payout time while the player is offline.
# Setting this value to 0 causes the multiplier to freeze until the player comes back online. It will remain the same as long as it is not reset.
# Setting this value to 1 causes the multiplier to iterate like normal, even when the player is offline (discouraged)
# Absolute values greater than 1 *are* allowed, but are to be used sparingly (-2 would decrease a player's multiplier by two stages for every missed payout)
# Type: int
# Default: 0
offline-multiplier-behavior:
    default: 0
    allow-override: true

# Set the behavior of the interest multiplier when the player makes a withdrawal.
# Setting this value to -1 causes the multiplier to decrease by one stage per withdrawal.
# Setting this value to 0 causes the multiplier to not be affected by withdrawals (discouraged)
# Setting this value to any positive integer causes the multiplier to be RESET when the player makes a withdrawal.
# Absolute values greater than 1 are, similarly to above, allowed but to be used sparingly.
# Type: int
# Default: 1
withdrawal-multiplier-behavior:
    default: 1
    allow-override: true

# Set the item with which a player can click a account to retrieve information.
# You can set this to an empty string ("") to disable this feature.
# Type: String, converted to ItemStack
# Default: "STICK"
account-info-item: "STICK"

# Set the price a player has to pay in order to create...
# Set this to 0 to disable creation fees.
# Type: double
creation-prices:
    bank:
        player: 100000
        admin: 0
    account:
        default: 2500
        allow-override: true
  
# Set the lowest account balance a player must have to earn interest on their account.
# Set this to 0 to disable this feature (also disables low-balance-fee).
# Type: double
minimum-account-balance:
    default: 10000
    allow-override: true

# Set the fee that must be played by the player if their account balance is below the minimum.
# Set this to 0 to disable this feature.
# Type: double
low-balance-fee:
    default: 5000
    allow-override: true

# Set whether the (current) account creation price should be refunded
# when the account is removed by its creator.
# Type: boolean
reimburse-creation:
    bank:
        player: false
        admin: false
    account:
        default: false
        allow-override: true

# Whether a bank owner should be able to create an account at their own bank.
# Type: boolean
# Default: false
allow-self-banking: false

# Set whether to require confirmation of remove commands.
# Type: boolean
# Default: true
confirm-on-remove: true

# Set whether to require confirmation of removeall commands.
# Type: boolean
# Default: true
confirm-on-removeall: true

# Set insurance for every account on the server in case of chest corruption (not expected).
# Account owners will be reimbursed what was lost up to this amount.
# Set this value to -1 for no limit.
# Type: long
insure-accounts-up-to: -1

# Set whether the plugin will check for updates on server start
# and notify permitted players on join.
# The command is not affected by this setting and will continue to
# check for updates.
# Type: boolean
# Default: true
enable-update-checker: true

# Set whether deposits/withdrawals, interest payouts, and debug logs should be saved in the database.
# Debug log file may become quite large!
# Type: boolean
enable-logs:
  transaction-log: true
  interest-log: true
  debug-log: true

# Set the maximum age for economy log entries in days.
# All log entries older than this will be deleted on server start.
# Set this to 0 to disable this feature.
# Type: int
# Default: 30
cleanup-log-days: 30

# Set whether various protection plugins should be hooked into (if installed)
# in order to allow or deny bank or account creation in certain locations.
enable-worldguard-integration: true
enable-griefprevention-integration: true
enable-worldedit-integration: true

# Set whether accounts should automatically be removed from the database if
# an error occurred while loading.
# (e.g. no chest, no space above chest, or unknown world)
remove-account-on-error: true

# Set the items for which a player will earn no interest in their account.
blacklist:
# - "DIORITE"


# Account limits are handled with permissions.
# A player with permission "bankingplugin.account.limit.X" has a limit of X accounts,
# a player with permission "bankingplugin.account.limit.*" does not have an account limit.
default-limits:

  # Set the amount of accounts that anyone who doesn't have a
  # specific permission may have.
  # If you don't want the players to have a limit by default set the value to -1.
  bank: 1
  account: 2

# Set the number of accounts a player may have at any given bank.
# For example, a value of 2 would allow a player to create no more than two accounts at a single bank.
# A third account would have to be created at a different bank.
# Type: int
# Default: 1
player-account-limit-per-bank: 1

# Bank revenue is based on both the interest generated by and the number of accounts at the bank. 
# Revenue is calculated with the expression R = ((base-percentage) + (rate-of-increase * ln(# of accounts at bank))) * (total interest)
# The bank owner's profit is the revenue minus the total interest, which is paid to the account owners.
# View the graph of the function with default values 0.95 and 0.03: https://www.desmos.com/calculator/eltmvbfnyz (the x-value at y = 1 represents 
# the number of accounts needed for the bank owner to make a profit, in this case 5. The y-value represents the revenue multiplier).
# Feel free to leave these values as they are if this overwhelms you.
bank-profit-margin:
    # The base percentage can be understood as how much money a bank owner makes with only one account at their bank (base-percentage * total interest).
    # A value <1.00 represents a loss, a value >1.00 represents a profit. This value minus 1.00 represents the profit margin (at one account)
    # The profit margin will only go up as more accounts are registered at the bank.
    base-percentage: 0.95
    # The rate of increase can be understood as how fast the profit margin will increase with more accounts at the bank. 0.01 to 0.05 is typical.
    rate-of-increase: 0.03

# Set whether the custom WorldGuard flag should be allowed by default.
worldguard-default-flag-value:
  create-bank: false
  
# Set the prefix of all SQLite table names related to this plugin.
table-prefix: "bankingplugin_"