# If you edit this file your face might melt off.

name: ${project.name}
main: com.monst.bankingplugin.BankingPlugin
version: ${project.version}
api-version: 1.15
database: true
author: FreshLlamanade
depend: [Vault, Essentials]
softdepend: [WorldEdit, GriefPrevention, WorldGuard]

permissions:
    bankingplugin.*:
        description: Gives access to all BankingPlugin features.
        default: op
        children:
            bankingplugin.account.*: true
            bankingplugin.bank.*: true
            bankingplugin.external.bypass: true
            bankingplugin.config: true
            bankingplugin.reload: true
            bankingplugin.update: true
    
    bankingplugin.account.*:
        description: Gives access to all account features.
        default: op
        children:
            bankingplugin.account.create: true
            bankingplugin.account.create.protected: true
            bankingplugin.account.trust: true
            bankingplugin.account.remove-other: true
            bankingplugin.account.info-other-verbose: true
            bankingplugin.account.list.other: true
            bankingplugin.account.list.other.verbose: true
            bankingplugin.account.view-other: true
            bankingplugin.account.edit-other: true
            bankingplugin.account.migrate-other: true
            bankingplugin.account.extend-other: true
            bankingplugin.account.limit.*: true
            bankingplugin.account.set.*: true
    
    bankingplugin.account.set.*:
        description: Gives access to all account configuration commands.
        default: op
        children:
            bankingplugin.account.set.nickname: true
            bankingplugin.account.set.nickname.other: true
            bankingplugin.account.set.multiplier: true
            bankingplugin.account.set.multiplier.other: true
            bankingplugin.account.set.delay-period: true
            bankingplugin.account.set.delay-period.other: true
    
    bankingplugin.bank.*:
        description: Gives access to all bank features.
        default: op
        children:
            bankingplugin.bank.create: true
            bankingplugin.bank.create.admin: true
            bankingplugin.bank.remove.other: true
            bankingplugin.bank.remove.admin: true
            bankingplugin.bank.removeall: true
            bankingplugin.bank.limit.*: true
            bankingplugin.bank.info.verbose: true
            bankingplugin.bank.list.verbose: true
            bankingplugin.bank.resize: true
            bankingplugin.bank.resize.other: true
            bankingplugin.bank.resize.admin: true
            bankingplugin.bank.set: true
            bankingplugin.bank.set.other: true
            bankingplugin.bank.set.admin: true
    
    
    # ACCOUNT #
    bankingplugin.account.create:
        description: Create and remove accounts.
        default: true
    bankingplugin.account.create.protected:
        description: Create an account on a protected chest or land claim.
        default: op
        children:
            bankingplugin.account.create: true
    bankingplugin.account.trust:
        description: Add or remove other players as co-owners of your account.
        default: true
    bankingplugin.account.remove-other:
        description: Remove another player's account.
        default: op
        
    bankingplugin.account.info-other-verbose:
        description: View detailed information about another player's account.
        default: op
        
    bankingplugin.account.list.other:
        description: View a list of other player's accounts.
        default: op
    
    bankingplugin.account.list.other.verbose:
        description: View a detailed list of other player's accounts.
        default: op
        children:
            bankingplugin.account.list.other: true
    
    bankingplugin.account.view-other:
        description: Look into another player's account chest.
        default: op
        
    bankingplugin.account.edit-other:
        description: Edit the contents of another player's account chest.
        default: op
        children:
            bankingplugin.account.view-other: true
            
    bankingplugin.account.extend.other:
        description: Extend another player's account chest.
        default: op
        
    bankingplugin.account.limit.*:
        description: Create an unlimited number of accounts.
        default: op
    
    # ACCOUNT.SET #
    bankingplugin.account.set.nickname:
        description: Set your account nickname.
        default: true
    
    bankingplugin.account.set.nickname.other:
        description: Set another player's account nickname.
        default: op
        children:
            bankingplugin.account.set.nickname: true
            
    bankingplugin.account.set.multiplier:
        description: Set your account multiplier.
        default: op
    
    bankingplugin.account.set.multiplier.other:
        description: Set another player's account multiplier.
        default: op
        children:
            bankingplugin.account.set.multiplier: true
            
    bankingplugin.account.set.delay-period:
        description: Set your account delay period.
        default: op
    
    bankingplugin.account.set.delay-period.other:
        description: Set another player's account interest delay period.
        default: op
        children:
            bankingplugin.account.set.delay-period: true
    
    
    # BANK #
    bankingplugin.bank.create:
        description: Create a bank.
        default: op
    bankingplugin.bank.create.admin:
        description: Create an admin bank.
        default: op
    bankingplugin.bank.remove.other:
        description: Remove another player's bank and all associated accounts.
        default: op
        children:
            bankingplugin.account.remove-other: true
    bankingplugin.bank.remove.admin:
        description: Remove an admin bank and all associated accounts.
        default: op
        children:
            bankingplugin.account.remove-other: true
    bankingplugin.bank.removeall:
        description: Remove all banks and all accounts.
        default: op
        children:
            bankingplugin.bank.remove.other: true
            bankingplugin.bank.remove.admin: true
            bankingplugin.account.remove-other: true
    bankingplugin.bank.limit.*:
        description: Create an unlimited number of banks.
        default: op
    bankingplugin.bank.info.verbose:
        description: View detailed bank info.
        default: true
    bankingplugin.bank.list.verbose:
        description: View a detailed list of banks.
        default: true
    bankingplugin.bank.resize:
        description: Resize an existing bank.
        default: op
    bankingplugin.bank.resize.other:
        description: Resize another player's bank.
        default: op
        children:
            bankingplugin.bank.resize: true
    bankingplugin.bank.resize.admin:
        description: Resize an admin bank.
        default: op
        children:
            bankingplugin.bank.resize.other: true
    bankingplugin.bank.set.other:
        description: Configure another player's bank.
        default: op
    bankingplugin.bank.set.admin:
        description: Configure an admin bank.
        default: op
        children:
            bankingplugin.bank.set.other: true
    
    bankingplugin.external.bypass:
        description: Bypass other plugins' attempts to stop you using this plugin.
        default: op
    bankingplugin.config:
        description: Manage the configuration of this plugin.
        default: op
    bankingplugin.reload:
        description: Reload this plugin.
        default: op
    bankingplugin.update:
        description: Update this plugin.
        default: op