# If you edit this file your face might melt off.

name: ${project.name}
main: com.monst.bankingplugin.BankingPlugin
version: ${project.version}
api-version: 1.15
database: true
author: monst
depend: [Vault, Essentials]
softdepend: [WorldEdit, GriefPrevention, WorldGuard]

permissions:
    bankingplugin.*:
        description: Gives access to all BankingPlugin features.
        default: op
        children:
            bankingplugin.account.*: true
            bankingplugin.bank.*: true
            bankingplugin.external-bypass: true
            bankingplugin.config: true
            bankingplugin.reload: true
            bankingplugin.update: true
            bankingplugin.pay-interest: true
    
    bankingplugin.account.*:
        description: Gives access to all account features.
        default: op
        children:
            bankingplugin.account.create: true
            bankingplugin.account.create.protected: true
            bankingplugin.account.trust: true
            bankingplugin.account.trust.other: true
            bankingplugin.account.remove-other: true
            bankingplugin.account.info-other: true
            bankingplugin.account.list-other: true
            bankingplugin.account.view-other: true
            bankingplugin.account.edit-other: true
            bankingplugin.account.migrate.other: true
            bankingplugin.account.migrate.bank: true
            bankingplugin.account.transfer: true
            bankingplugin.account.transfer.other: true
            bankingplugin.account.extend-other: true
            bankingplugin.account.limit.*: true
            bankingplugin.account.set.*: true
    
    bankingplugin.account.set.*:
        description: Gives access to all account configuration commands.
        default: op
        children:
            bankingplugin.account.set.nickname-other: true
            bankingplugin.account.set.multiplier: true
            bankingplugin.account.set.delay-period: true
    
    bankingplugin.bank.*:
        description: Gives access to all bank features.
        default: op
        children:
            bankingplugin.bank.create: true
            bankingplugin.bank.create.admin: true
            bankingplugin.bank.remove.other: true
            bankingplugin.bank.remove.admin: true
            bankingplugin.bank.removeall: true
            bankingplugin.bank.limit.*: true
            bankingplugin.bank.size.*: true
            bankingplugin.bank.info.other: true
            bankingplugin.bank.info.admin: true
            bankingplugin.bank.resize.other: true
            bankingplugin.bank.resize.admin: true
            bankingplugin.bank.transfer: true
            bankingplugin.bank.transfer.other: true
            bankingplugin.bank.transfer.admin: true
            bankingplugin.bank.set.other: true
            bankingplugin.bank.set.admin: true
    
    
    # ACCOUNT #
    bankingplugin.account.create:
        description: Create, migrate, set nicknames for, and remove accounts of your own.
        default: true
        
    bankingplugin.account.create.protected:
        description: Create (or extend) an account where chest access is prohibited by another plugin.
        default: op
        children:
            bankingplugin.account.create: true
            
    bankingplugin.account.trust:
        description: Add or remove other players as co-owners of your account.
        default: true
        
    bankingplugin.account.trust.other:
        description: Add or remove other players as co-owners of another player's account.
        default: op
        children:
            bankingplugin.account.trust: true
        
    bankingplugin.account.remove-other:
        description: Remove another player's account.
        default: op
        
    bankingplugin.account.info-other:
        description: View detailed information about another player's account.
        default: op
        
    bankingplugin.account.list-other:
        description: View a list of other players' accounts.
        default: op
    
    bankingplugin.account.view-other:
        description: Look into another player's account chest.
        default: op
        
    bankingplugin.account.edit-other:
        description: Edit the contents of another player's account chest.
        default: op
        children:
            bankingplugin.account.view-other: true
    
    bankingplugin.account.migrate.other:
        description: Migrate another player's account chest to another chest.
        default: op
        children:
            bankingplugin.account.create: true
        
    bankingplugin.account.migrate.bank:
        description: Migrate an account to another chest in a different bank.
        default: op
        children:
            bankingplugin.account.create: true
    
    bankingplugin.account.transfer:
        description: Transfer ownership of your account to another player.
        default: true
        children:
            bankingplugin.account.create: true
    
    bankingplugin.account.transfer.other:
        description: Transfer ownership of another player's account to another player (or yourself).
        default: op
        children:
            bankingplugin.account.transfer: true
            
    bankingplugin.account.extend-other:
        description: Extend another player's account chest.
        default: op
        
    bankingplugin.account.limit.*:
        description: Create an unlimited number of accounts.
        default: op
    
    # ACCOUNT.SET #
    bankingplugin.account.set.nickname-other:
        description: Set another player's account nickname.
        default: op
        
    bankingplugin.account.set.multiplier:
        description: Set the multiplier of any account.
        default: op
        
    bankingplugin.account.set.interest-delay:
        description: Set the interest delay period of any account.
        default: op    
    
    # BANK #
    bankingplugin.bank.create:
        description: Create, manage, and remove banks of your own.
        default: true
        
    bankingplugin.bank.create.admin:
        description: Create, manage, and remove admin banks.
        default: op
        
    bankingplugin.bank.remove.other:
        description: Remove another player's bank and all associated accounts.
        default: op
        children:
            bankingplugin.account.remove-other: true
            
    bankingplugin.bank.remove.admin:
        description: Remove an admin bank and all associated accounts.
        default: op
        children:
            bankingplugin.bank.remove.other: true
            
    bankingplugin.bank.removeall:
        description: Remove all banks and all accounts.
        default: op
        children:
            bankingplugin.bank.remove.admin: true
            
    bankingplugin.bank.limit.*:
        description: Create an unlimited number of banks.
        default: op
        
    bankingplugin.bank.size.*:
        description: Create a bank of unlimited volume.
        default: op
        
    bankingplugin.bank.info.other:
        description: View detailed information about another player's bank.
        default: op
        
    bankingplugin.bank.info.admin:
        description: View detailed information about an admin bank.
        default: op
        
    bankingplugin.bank.resize.other:
        description: Resize another player's bank.
        default: op
        children:
            bankingplugin.bank.create: true
        
    bankingplugin.bank.resize.admin:
        description: Resize an admin bank.
        default: op
        children:
            bankingplugin.bank.resize.other: true
            
    bankingplugin.bank.transfer:
        description: Transfer ownership of your bank to another player.
        default: true
        children:
            bankingplugin.bank.create: true
    
    bankingplugin.bank.transfer.other:
        description: Transfer ownership of another player's account to another player (or yourself).
        default: op
        children:
            bankingplugin.bank.transfer: true
    
    bankingplugin.bank.transfer.admin:
        description: Transfer ownership of an admin bank to another player (or yourself).
        default: op
        children:
            bankingplugin.bank.transfer.other: true
    
    bankingplugin.bank.set.other:
        description: Configure another player's bank.
        default: op
        
    bankingplugin.bank.set.admin:
        description: Configure an admin bank.
        default: op
        children:
            bankingplugin.bank.set.other: true
    
    # CONTROL #
    bankingplugin.external-bypass:
        description: Bypass other plugins' attempts to selectively prevent functionality of this plugin.
        default: op
        
    bankingplugin.config:
        description: Configure this plugin.
        default: op
        
    bankingplugin.reload:
        description: Reload this plugin.
        default: op
        
    bankingplugin.update:
        description: Update this plugin.
        default: op
        
    bankingplugin.pay-interest:
        description: Manually trigger an interest payment.
        default: op